interfaces {
    {% for (if_name) in if_s %}
        {{if_name}} {
            unit 0 {
                family inet {
                }
            }
        }
    {% endfor %}
}

protocols {
    lldp {
        interface all;
    }
}

security {
    zones {
        security-zone trust {
            interfaces {
                {% for (if_name) in if_s %}
                    {{if_name}} {
                        host-inbound-traffic {
                            system-services {
                                ssh;
                                telnet;
                                ping;
                            }
                        }
                    }
                {% endfor %}
            }
        }
    }
}
